api:
  api_key: "YYYtxMp7ykO4rxJwZsAVQcT4fMZW1DPj"
  base_url: "https://api.tomorrow.io/v4/weather/realtime"

locations:
  - name: Gachibowli
    lat: 17.4401
    lon: 78.3489
  - name: Hitech_City
    lat: 17.4474
    lon: 78.3762
  - name: Madhapur
    lat: 17.4483
    lon: 78.3915
  - name: Kukatpally
    lat: 17.4948
    lon: 78.3996
  - name: Miyapur
    lat: 17.4958
    lon: 78.3560
  - name: Ameerpet
    lat: 17.4375
    lon: 78.4483
  - name: SR_Nagar
    lat: 17.4426
    lon: 78.4520
  - name: Secunderabad
    lat: 17.4399
    lon: 78.4983
  - name: Begumpet
    lat: 17.4447
    lon: 78.4660
  - name: Punjagutta
    lat: 17.4294
    lon: 78.4505
  - name: Mehdipatnam
    lat: 17.3950
    lon: 78.4314
  - name: Tolichowki
    lat: 17.4000
    lon: 78.4183
  - name: LB_Nagar
    lat: 17.3456
    lon: 78.5522
  - name: Uppal
    lat: 17.4056
    lon: 78.5599
  - name: Dilsukhnagar
    lat: 17.3683
    lon: 78.5242
  - name: Tarnaka
    lat: 17.4270
    lon: 78.5310
  - name: Nacharam
    lat: 17.4220
    lon: 78.5489
  - name: Kompally
    lat: 17.5449
    lon: 78.4861
  - name: Alwal
    lat: 17.4963
    lon: 78.5146
  - name: Banjara_Hills
    lat: 17.4126
    lon: 78.4481

fields:
  - temperature
  - temperatureApparent
  - temperatureMin
  - temperatureMax
  - humidity
  - dewPoint
  - pressureSurfaceLevel
  - windSpeed
  - windDirection
  - windGust
  - precipitationIntensity
  - precipitationProbability
  - rainAccumulation
  - cloudCover
  - visibility
  - observationTime
